name: uberClone
options:
  bundleIdPrefix: com.devmeist3r
  createIntermediateGroups: true
  generateEmptyDirectories: true
  developmentLanguage: en
  postGenCommand: pod install
targets:
  uberClone:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources: [uberClone]